title: Sivanagaraju Kodali
logo: /assets/img/headshot_circle.png
description: >
  Master's in Information Systems | Aspiring AI Engineer  
  Skilled in Python, AWS, and Machine Learning  
  Passionate about building intelligent systems
show_downloads: true
theme: jekyll-theme-minimal

# Social links
github_username: ksqq1
linkedin: https://www.linkedin.com/in/sivanagaraju-kodali-6a2902400/
email: sivanagarajukodali21@example.com
